source "http://rubygems.org"

gem "sinatra",         "~> 1.1.0"
gem "haml",            "~> 3.0.23"
gem "memcache-client", "~> 1.8.5"
gem "yajl-ruby",       "~> 0.7.8"
gem "activerecord",    "~> 3.0.1"
gem "mustache",        "~> 0.11.2"
gem "faraday",         "~> 0.5.3"
gem "oauth2",          "~> 0.1.0"
gem "typhoeus",        "~> 0.1.31"